# Generated by Django 4.2.5 on 2023-11-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
