# Generated by Django 4.2.5 on 2023-11-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_timeslot_username_timeslot_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('carModel', models.CharField(max_length=50)),
                ('carColor', models.CharField(max_length=50)),
                ('licensePlate', models.CharField(max_length=50)),
            ],
        ),
    ]
