# Generated by Django 4.2.5 on 2023-11-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_driver_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
