# Generated by Django 4.2.7 on 2023-11-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_driver_firstname_remove_driver_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
