# Generated by Django 4.2.5 on 2023-12-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_flightinformation_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="google_id",),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driver", name="user", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
